# Generated by Django 4.1.3 on 2023-02-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_catidad_id_lineapedido_catidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'ordering': ['id'], 'verbose_name': 'Línea Pedido', 'verbose_name_plural': 'Líneas Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='catidad',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
